export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOAD_ALL_MATCHES = "LOAD_ALL_MATCHES";

export const LOAD_ALL_CONTEST = "LOAD_ALL_CONTEST";
export const JOIN_LEAGUE = "JOIN_LEAGUE";
export const LOAD_USER_LEAGUES = "LOAD_USER_LEAGUES";
export const LOAD_LEAGUES_USER_DETAILS ="LOAD_LEAGUES_USER_DETAILS";


